### PR TITLE
UI improvements

### LINKED ISSUE #6: UI improvements
screen shot 2018-08-11 at 6 28 44 pm
screen shot 2018-08-11 at 6 28 48 pm
screen shot 2018-08-11 at 6 28 52 pm
screen shot 2018-08-11 at 6 29 00 pm
screen shot 2018-08-11 at 6 28 58 pm
screen shot 2018-08-11 at 6 28 55 pm

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
fixes #6

### CODE REVIEW

**Comment by abhishek97** [comment]
@VibhorCodecianGupta add screenshots

**Comment by VibhorCodecianGupta** [comment]
Will do within an hour or so. Not near my machine rn. Plis don't close the issue before then :3

Thanks.

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 Will do within an hour or so. Not near my machine rn. Plis don't close the issue before then, could really use some competition on that bounty :3

Thanks.

**Comment by VibhorCodecianGupta** [comment]
- screen shot 2018-08-12 at 7 13 54 pm

- screen shot 2018-08-12 at 7 14 29 pm

- screen shot 2018-08-12 at 7 37 42 pm

- screen shot 2018-08-12 at 8 11 08 pm

**Comment by abhishek97** [comment]
@VibhorCodecianGupta We also need markdown previews of text in the tile and description fields for quiz and questions. Please include those too.

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 any issues with this? was solving the markdown problem rn

**Comment by abhishek97** [comment]
@VibhorCodecianGupta Not really, merged the earlier one.

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 this was looking cleaner tho. Anyway, whichever you see fit

**Pull request closed without merging**
