### PR TITLE
Improve UI

### PR DESCRIPTION
**Pull request by Dhroov7**
screen shot 2018-08-10 at 5 43 31 pm
screen shot 2018-08-10 at 5 43 03 pm
screen shot 2018-08-10 at 5 43 12 pm
screen shot 2018-08-10 at 5 43 15 pm
screen shot 2018-08-10 at 5 43 18 pm
screen shot 2018-08-10 at 5 43 22 pm
screen shot 2018-08-10 at 5 43 27 pm

### CODE REVIEW

**Comment by abhishek97** [comment]
@Dhroov7 fix conflicts. just ignore yarn.lock and don't commit it.

**Comment by Dhroov7** [comment]
@abhishek97 Done.

**Comment by abhishek97** [comment]
@Dhroov7 Fix paddings in textboxes. In many places the text is too close to the top.

**Comment by Dhroov7** [comment]
@abhishek97 Please review.

**Pull request merged**
